# Generated by Django 4.0.4 on 2022-05-16 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='DateTime this record was created.')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='DateTime this record last updated.')),
                ('is_calculated', models.BooleanField(default=False, help_text='False by default, or when manually cast - True, if calculated by the system.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='DateTime this record was created.')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='DateTime this record last updated.')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_winning_candidate', models.BooleanField(default=False, help_text='Set by tally (and note: there might be a tie)')),
                ('stars', models.PositiveSmallIntegerField(default=0, help_text='Score Then Automatic Runoff', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='DateTime this record was created.')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='DateTime this record last updated.')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='DateTime this record was created.')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='DateTime this record last updated.')),
                ('stars', models.PositiveSmallIntegerField(default=0, help_text='Score Then Automatic Runoff', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='communities.ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='communities.candidate')),
            ],
            options={
                'ordering': ['candidate'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='DateTime this record was created.')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='DateTime this record last updated.')),
                ('is_anonymous', models.BooleanField(default=True, help_text='Members vote anonymously by default.')),
                ('is_community_legislator', models.BooleanField(default=False, help_text='Can author and publish Elections.')),
                ('is_community_manager', models.BooleanField(default=False, help_text='Can manage Community membership.')),
                ('is_voting_community_member', models.BooleanField(default=False, help_text='Can vote (not just a lobbyist.)')),
                ('dt_joined', models.DateTimeField(auto_now_add=True, help_text='DateTime member joined this community')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='communities.community')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='DateTime this record was created.')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='DateTime this record last updated.')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dt_close', models.DateTimeField(help_text='DateTime this Election closes, no longer tallied, and no longer allowing votes.')),
                ('ballot_tree', models.TextField(help_text='JSON data representation of the tally')),
                ('tally_report', models.TextField(help_text='User-friendly presentation of the ballot_tree')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='communities.community')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(through='communities.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='communities.election'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='communities.election'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
