# Generated by Django 4.0.4 on 2022-05-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballot',
            old_name='calculated',
            new_name='is_calculated',
        ),
    ]
