# Generated by Django 5.2.6 on 2025-09-06 02:36

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tags that characterize this ballot for delegation purposes', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='UUIDTaggedItem',
        ),
    ]
