# Generated by Django 5.2.6 on 2025-10-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('democracy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='voter',
            field=models.ForeignKey(help_text='The user who cast this ballot (or had it calculated)', on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decision',
            name='community',
            field=models.ForeignKey(help_text='The community this decision belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='democracy.community'),
        ),
        migrations.AddField(
            model_name='choice',
            name='decision',
            field=models.ForeignKey(help_text='The decision this choice belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='democracy.decision'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='decision',
            field=models.ForeignKey(help_text='The decision this ballot is voting on', on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='democracy.decision'),
        ),
        migrations.AddField(
            model_name='decisionsnapshot',
            name='decision',
            field=models.ForeignKey(help_text='The decision this snapshot represents', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='democracy.decision'),
        ),
        migrations.AddField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(help_text='The community this membership belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='democracy.community'),
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(help_text='The user who is a member of this community', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(help_text='Users who belong to this community', through='democracy.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='decision',
            field=models.ForeignKey(help_text='The decision these results are for', on_delete=django.db.models.deletion.PROTECT, related_name='results', to='democracy.decision'),
        ),
        migrations.AddField(
            model_name='vote',
            name='ballot',
            field=models.ForeignKey(help_text='The ballot this vote belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='democracy.ballot'),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(help_text='The choice being rated in this vote', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='democracy.choice'),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('decision', 'voter')},
        ),
        migrations.AddIndex(
            model_name='decisionsnapshot',
            index=models.Index(fields=['decision', '-created_at'], name='democracy_d_decisio_b3fb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionsnapshot',
            index=models.Index(fields=['decision', 'is_final'], name='democracy_d_decisio_349222_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('choice', 'ballot')},
        ),
    ]
