# Generated by Django 5.2.6 on 2025-10-08 12:23
"""
Migration to implement membership-level anonymity.

This migration:
1. Renames Membership.is_anonymous_by_default to is_anonymous
2. Adds a database constraint ensuring lobbyists cannot be anonymous
3. Removes is_anonymous field from Ballot model (ballot-level anonymity removed)

Rationale:
- Anonymity is now controlled at the membership level (per-community)
- Lobbyists must be public to build reputation and seek followers
- Simplifies the anonymity system while maintaining auditability
"""

from django.db import migrations, models
from django.db.models import Q


def fix_lobbyist_anonymity(apps, schema_editor):
    """
    Data migration to set is_anonymous=False for all lobbyists.
    
    Lobbyists (members with is_voting_community_member=False) cannot be anonymous
    because they are building reputation and seeking followers. This ensures existing
    data complies with the new constraint.
    """
    Membership = apps.get_model('democracy', 'Membership')
    
    # Find all lobbyists (non-voting members) who are currently anonymous
    lobbyists_to_fix = Membership.objects.filter(
        is_voting_community_member=False,
        is_anonymous=True
    )
    
    count = lobbyists_to_fix.count()
    if count > 0:
        # Set all lobbyists to public (is_anonymous=False)
        lobbyists_to_fix.update(is_anonymous=False)
        print(f"Fixed {count} lobbyist(s) by setting is_anonymous=False")


def reverse_lobbyist_fix(apps, schema_editor):
    """Reverse migration - no action needed as we can't restore previous anonymity preferences."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0002_initial'),
    ]

    operations = [
        # Rename is_anonymous_by_default to is_anonymous on Membership model
        migrations.RenameField(
            model_name='membership',
            old_name='is_anonymous_by_default',
            new_name='is_anonymous',
        ),
        
        # Update help text for the renamed field
        migrations.AlterField(
            model_name='membership',
            name='is_anonymous',
            field=models.BooleanField(
                default=True,
                help_text="Whether this member's identity is anonymous in this community"
            ),
        ),
        
        # Data migration: Fix existing lobbyists before adding constraint
        migrations.RunPython(fix_lobbyist_anonymity, reverse_lobbyist_fix),
        
        # Add constraint: Lobbyists (is_voting_community_member=False) cannot be anonymous
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(
                check=Q(is_voting_community_member=True) | Q(is_anonymous=False),
                name='lobbyists_cannot_be_anonymous'
            ),
        ),
        
        # Remove is_anonymous field from Ballot model (no longer needed)
        migrations.RemoveField(
            model_name='ballot',
            name='is_anonymous',
        ),
    ]
