# Generated by Django 5.2.6 on 2025-09-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0002_alter_ballot_tags_delete_uuidtaggeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='tags',
        ),
    ]
