# Generated by Django 5.2.6 on 2025-09-06 02:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0003_remove_ballot_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='comments',
            field=models.TextField(blank=True, help_text='Optional explanation of voting reasoning or context'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='decision',
            field=models.ForeignKey(help_text='The decision this ballot is voting on', on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='democracy.decision'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this ballot', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='is_anonymous',
            field=models.BooleanField(default=True, help_text='Whether this ballot should be kept anonymous'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='is_calculated',
            field=models.BooleanField(default=False, help_text='True if calculated by delegation system, False if manually cast'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='voter',
            field=models.ForeignKey(help_text='The user who cast this ballot (or had it calculated)', on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='decision',
            field=models.ForeignKey(help_text='The decision this choice belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='democracy.decision'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='description',
            field=models.TextField(help_text='Detailed description of what this choice represents'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='runoff_score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Score in the automatic runoff phase of STAR voting', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Average star score from all votes (0.0000-5.0000)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(help_text='Short, descriptive name for this choice', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(help_text="Detailed description of the community's purpose and scope"),
        ),
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(help_text='Users who belong to this community', through='democracy.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(help_text='Display name of the community', max_length=255),
        ),
        migrations.AlterField(
            model_name='decision',
            name='community',
            field=models.ForeignKey(help_text='The community this decision belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='democracy.community'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='description',
            field=models.TextField(help_text="Detailed description of what's being decided, including context and implications"),
        ),
        migrations.AlterField(
            model_name='decision',
            name='dt_close',
            field=models.DateTimeField(help_text='When voting closes and results are finalized (no more votes accepted)'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='decision',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='results_need_updating',
            field=models.BooleanField(default=True, help_text='Whether results need recalculation (set when new votes are cast)'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='title',
            field=models.CharField(help_text='Short, descriptive title of the decision', max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(help_text='The community this membership belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='democracy.community'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='dt_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this member joined the community'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_anonymous_by_default',
            field=models.BooleanField(default=True, help_text='Whether this member prefers anonymous voting by default'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_community_manager',
            field=models.BooleanField(default=False, help_text='Whether this member can manage community membership and settings'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_voting_community_member',
            field=models.BooleanField(default=False, help_text="Whether this member's votes count (vs. being just a lobbyist)"),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(help_text='The user who is a member of this community', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='result',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='result',
            name='decision',
            field=models.ForeignKey(help_text='The decision these results are for', on_delete=django.db.models.deletion.PROTECT, related_name='results', to='democracy.decision'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='result',
            name='report',
            field=models.TextField(help_text='Human-readable summary of the voting results and winner'),
        ),
        migrations.AlterField(
            model_name='result',
            name='stats',
            field=models.JSONField(help_text='Detailed statistics including vote counts, averages, delegation chains, and audit data'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ballot',
            field=models.ForeignKey(help_text='The ballot this vote belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='democracy.ballot'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(help_text='The choice being rated in this vote', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='democracy.choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this vote', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='stars',
            field=models.PositiveSmallIntegerField(default=0, help_text='Star rating from 0 (worst) to 5 (best) for this choice', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('decision', 'voter')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('choice', 'ballot')},
        ),
    ]
