# Generated by Django 5.2.6 on 2025-10-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0003_membership_anonymity'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionsnapshot',
            name='tally_log',
            field=models.JSONField(blank=True, default=dict, help_text='Complete log of STAR voting tally process with score and runoff details'),
        ),
        migrations.AddField(
            model_name='decisionsnapshot',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='The winning choice determined by STAR voting tally (set after tally completes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_snapshots', to='democracy.choice'),
        ),
    ]
