# Generated by Django 5.2.6 on 2025-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0004_alter_ballot_comments_alter_ballot_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags this voter applied to characterize this decision (e.g., 'environmental,fiscal')", max_length=500),
        ),
    ]
