# Generated by Django 5.2.6 on 2025-09-06 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0005_add_tags_to_ballot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVoteMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified')),
                ('anonymous_guid', models.UUIDField(default=uuid.uuid4, help_text='The GUID displayed in public reports instead of the username')),
                ('decision', models.ForeignKey(help_text='The decision this anonymous mapping applies to', on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_mappings', to='democracy.decision')),
                ('user', models.ForeignKey(help_text='The actual user who is voting anonymously', on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anonymous Vote Mapping',
                'verbose_name_plural': 'Anonymous Vote Mappings',
                'db_table': 'democracy_anonymous_vote_mapping',
                'ordering': ['-created'],
                'unique_together': {('decision', 'user')},
            },
        ),
    ]
