# Generated by Django 5.2.6 on 2025-09-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0006_add_anonymous_vote_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='application_message_required',
            field=models.BooleanField(default=False, help_text='Require application message from users when applying'),
        ),
        migrations.AddField(
            model_name='community',
            name='auto_approve_applications',
            field=models.BooleanField(default=False, help_text='Automatically approve membership applications (demo mode)'),
        ),
        migrations.AddField(
            model_name='community',
            name='member_count_display',
            field=models.BooleanField(default=True, help_text='Show member count publicly on community pages'),
        ),
    ]
