# Generated by Django 5.2.6 on 2025-09-07 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0007_add_community_management_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was calculated')),
                ('snapshot_data', models.JSONField(default=dict, help_text='Complete system state and calculation results at snapshot time')),
                ('calculation_duration', models.DurationField(blank=True, help_text='How long the calculation took to complete', null=True)),
                ('total_eligible_voters', models.IntegerField(default=0, help_text='Number of voting community members at snapshot time')),
                ('total_votes_cast', models.IntegerField(default=0, help_text='Number of direct votes submitted by users')),
                ('total_calculated_votes', models.IntegerField(default=0, help_text='Number of votes calculated via delegation chains')),
                ('tags_used', models.JSONField(default=list, help_text='All tags used in voting with frequency counts')),
                ('is_final', models.BooleanField(default=False, help_text='True when decision is closed and results are final')),
                ('decision', models.ForeignKey(help_text='The decision this snapshot represents', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='democracy.decision')),
            ],
            options={
                'verbose_name': 'Decision Snapshot',
                'verbose_name_plural': 'Decision Snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision', '-created_at'], name='democracy_d_decisio_b3fb2b_idx'), models.Index(fields=['decision', 'is_final'], name='democracy_d_decisio_349222_idx')],
            },
        ),
    ]
