# Generated by Django 5.2.6 on 2025-09-10 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0009_make_choice_description_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags this voter applied to characterize this decision (e.g., 'environmental,fiscal')", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='runoff_score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Score in the automatic runoff phase of STAR voting', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Average star score from all votes (0.0000-5.0000)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
