# Generated by Django 5.2.6 on 2025-09-10 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0010_alter_ballot_tags_alter_choice_runoff_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='runoff_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Score in the automatic runoff phase of STAR voting', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Average star score from all votes (0.0000-5.0000)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
