# Generated by Django 5.2.6 on 2025-09-12 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0011_alter_choice_runoff_score_alter_choice_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='stars',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Star rating from 0.00 (worst) to 5.00 (best) for this choice - supports fractional ratings from delegation averaging', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
