# Generated by Django 5.2.6 on 2025-09-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0012_change_vote_stars_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionsnapshot',
            name='calculation_status',
            field=models.CharField(choices=[('creating', 'Creating Snapshot'), ('ready', 'Ready for Calculation'), ('staging', 'Stage Ballots in Progress'), ('tallying', 'Tally in Progress'), ('completed', 'Calculation Completed'), ('failed_snapshot', 'Snapshot Creation Failed'), ('failed_staging', 'Stage Ballots Failed'), ('failed_tallying', 'Tally Failed'), ('corrupted', 'Snapshot Corrupted')], default='ready', help_text='Current status of the calculation process', max_length=20),
        ),
        migrations.AddField(
            model_name='decisionsnapshot',
            name='error_log',
            field=models.TextField(blank=True, help_text='Detailed error information if calculation failed'),
        ),
        migrations.AddField(
            model_name='decisionsnapshot',
            name='last_error',
            field=models.DateTimeField(blank=True, help_text='When the last error occurred during calculation', null=True),
        ),
        migrations.AddField(
            model_name='decisionsnapshot',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retry attempts for failed calculations'),
        ),
    ]
