# Generated by Django 5.2.6 on 2025-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0013_add_snapshot_error_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionsnapshot',
            name='snapshot_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete system state and calculation results at snapshot time'),
        ),
        migrations.AlterField(
            model_name='decisionsnapshot',
            name='tags_used',
            field=models.JSONField(blank=True, default=list, help_text='All tags used in voting with frequency counts'),
        ),
    ]
