# Generated by Django 5.2.6 on 2025-09-16 for Plan #23: Simplified Anonymity System

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0015_add_hashed_username_anonymity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousVoteMapping',
        ),
    ]
