# Generated by Django 5.2.6 on 2025-09-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='tags',
        ),
    ]
