# Generated by Django 5.2.6 on 2025-09-06 02:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_following_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='following',
            name='followee',
            field=models.ForeignKey(help_text='The user being followed (receiving delegated voting power).', on_delete=django.db.models.deletion.PROTECT, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(help_text='The user doing the following (delegating their vote).', on_delete=django.db.models.deletion.PROTECT, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='following',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='following',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
    ]
