# Generated by Django 5.2.6 on 2025-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_following_created_alter_following_followee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'ordering': ['follower__username', 'order', 'followee__username'], 'verbose_name': 'Following Relationship', 'verbose_name_plural': 'Following Relationships'},
        ),
        migrations.AddField(
            model_name='following',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Priority order for tie-breaking (lower numbers = higher priority)'),
        ),
        migrations.AddField(
            model_name='following',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags to follow this user on (e.g., 'environmental,fiscal'). Empty = follow on all tags.", max_length=500),
        ),
    ]
