# Generated by Django 5.2.6 on 2025-09-06 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_tags_and_order_to_following'),
        ('democracy', '0005_add_tags_to_ballot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by User')], default='pending', help_text='Current status of the membership application', max_length=20)),
                ('application_message', models.TextField(blank=True, help_text='Optional message from the user explaining why they want to join')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Optional notes from the reviewer about their decision')),
                ('community', models.ForeignKey(help_text='The community the user wants to join', on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to='democracy.community')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Community manager who reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user applying for community membership', on_delete=django.db.models.deletion.CASCADE, related_name='community_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Application',
                'verbose_name_plural': 'Community Applications',
                'ordering': ['-created'],
                'unique_together': {('user', 'community')},
            },
        ),
    ]
