# Generated by Django 5.2.6 on 2025-09-06 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_communityapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified')),
                ('email', models.EmailField(help_text='Email address this magic link was sent to', max_length=254)),
                ('token', models.CharField(help_text='Secure random token for the magic link URL', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this magic link expires and becomes invalid')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this magic link was successfully used (null if unused)', null=True)),
                ('created_user', models.ForeignKey(blank=True, help_text='User account that was created using this magic link', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magic Link',
                'verbose_name_plural': 'Magic Links',
                'ordering': ['-created'],
            },
        ),
    ]
