# Generated by Django 5.2.6 on 2025-09-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_magiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief biography to help other members understand your background and expertise', max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_public',
            field=models.BooleanField(default=True, help_text='Whether your biography is visible to other community members'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text="Your city, state/province, country (e.g., 'San Francisco, CA, USA')", max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_public',
            field=models.BooleanField(default=True, help_text='Whether your location is visible to other community members'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_links_public',
            field=models.BooleanField(default=True, help_text='Whether your social media links are visible to other community members'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Your Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True, help_text='Your personal website, blog, or professional page'),
        ),
    ]
