# Generated by Django 5.2.6 on 2025-09-10 13:27

from django.db import migrations


def remove_duplicate_following_relationships(apps, schema_editor):
    """Remove duplicate Following relationships to prepare for unique constraint."""
    Following = apps.get_model('accounts', 'Following')
    
    # Find duplicates based on follower, followee, and tags
    seen = set()
    duplicates_to_delete = []
    
    for following in Following.objects.all().order_by('id'):
        key = (following.follower_id, following.followee_id, following.tags)
        if key in seen:
            duplicates_to_delete.append(following.id)
        else:
            seen.add(key)
    
    # Delete duplicates (keep the first occurrence of each)
    Following.objects.filter(id__in=duplicates_to_delete).delete()
    print(f"Removed {len(duplicates_to_delete)} duplicate Following relationships")


def reverse_remove_duplicates(apps, schema_editor):
    """This migration cannot be reversed - duplicates are permanently removed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_profile_fields'),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_following_relationships,
            reverse_remove_duplicates,
        ),
    ]
