# Generated by Django 5.2.6 on 2025-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_duplicate_following'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('follower', 'followee', 'tags'), name='unique_following_relationship'),
        ),
    ]
