# Generated by Django 5.2.6 on 2025-09-16 for Plan #23: Simplified Anonymity System

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_following_unique_following_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vote_anonymously_by_default',
            field=models.BooleanField(default=False, help_text='Default anonymity preference for new votes across all communities'),
        ),
    ]
